language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm run test -- --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: npm
  email: "dionmaicon@outlook.com"
  api_key: $npm_token
  tag: beta
